In [2]:
import numpy as np

In [3]:
np.__version__

'2.2.4'

## Create & Read

### 1D Array

In [4]:
arr1 = np.array([1, 2, 3, 4, 5, 6])
arr1

array([1, 2, 3, 4, 5, 6])

In [5]:
type(arr1)

numpy.ndarray

In [6]:
arr1.shape

(6,)

In [7]:
arr1.dtype

dtype('int64')

In [8]:
arr1.ndim

1

In [9]:
arr1.size

6

In [10]:
arr1.size

6

### 2D Array

In [11]:
arr2 = np.array([[1, 4, 5], [6, 7, 4]])
arr2

array([[1, 4, 5],
       [6, 7, 4]])

In [12]:
arr2.ndim

2

In [13]:
arr2.shape # (row, col)

(2, 3)

In [14]:
arr2.dtype

dtype('int64')

In [15]:
arr2.size

6

### 3D Array

In [16]:
arr3 = np.array([[[1, 4, 5], [6, 7, 4]], [[3, 5, 4], [5, 8, 7]], [[1, 4, 5], [6, 7, 4]]])

In [17]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [18]:
arr3.ndim

3

In [19]:
arr3.shape

(3, 2, 3)

In [20]:
arr3.size

18

### Create random array

In [21]:
randomArr = np.random.rand(3, 2, 3)
randomArr

array([[[0.48775489, 0.82269246, 0.88815418],
        [0.62642765, 0.80145943, 0.04859443]],

       [[0.68013731, 0.82040418, 0.59845045],
        [0.79579497, 0.95072411, 0.31669442]],

       [[0.48407456, 0.70595024, 0.06505464],
        [0.8128542 , 0.90448146, 0.10902431]]])

In [22]:
randomArr.dtype

dtype('float64')

In [23]:
zeroes = np.zeros((3, 2, 3))
zeroes

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [24]:
zeroes.ndim

3

In [25]:
full = np.full((3, 2, 3), 9)
full

array([[[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]],

       [[9, 9, 9],
        [9, 9, 9]]])

In [26]:
ones = np.ones((3, 2, 3))
ones

array([[[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]],

       [[1., 1., 1.],
        [1., 1., 1.]]])

In [27]:
arr3

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]],

       [[1, 4, 5],
        [6, 7, 4]]])

In [31]:
arr3[0]

array([[1, 4, 5],
       [6, 7, 4]])

In [34]:
arr3[0:2]

array([[[1, 4, 5],
        [6, 7, 4]],

       [[3, 5, 4],
        [5, 8, 7]]])

In [35]:
arr3[-1]

array([[1, 4, 5],
       [6, 7, 4]])

In [36]:
arr3[1][0][1]

np.int64(5)

In [37]:
arr3[1, 0, 1]

np.int64(5)